# Site settings
title: Bowen
email: fantastic.bowen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Copyright ©2015 All Rights Reserved.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bowenz.github.io/" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  BowenZ
encoding: UTF-8
# Build settings
markdown: kramdown
highlighter: pygments

paginate: 5   #这里指定你每一页的文章数目，我这里指定每页最多2篇文章
paginate_path: "/page:num/"   #这里是分页链接的格式，例如第二页会显示在'/page2/'