# Site settings
title: Bowen
email: fantastic.bowen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bowenz.github.io/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
encoding: UTF-8
# Build settings
markdown: kramdown
highlighter: pygments

paginate: 5   #这里指定你每一页的文章数目，我这里指定每页最多2篇文章
paginate_path: "/page:num/"   #这里是分页链接的格式，例如第二页会显示在'/page2/'